services:
  fr_dashboard_server:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fr_dashboard_server
    env_file:
      - ../.env
    environment:
      APP_ROLE: server
    ports:
      - "5000:5000"
    volumes:
      - ../data:/app/data
    restart: unless-stopped
